database:
  mysql:
    sdb:
      host: 127.0.0.1
      port: 3306
      username: root
      password: 
      dbname: sdb
      adapter: mysql
    miniproject:
      host: 127.0.0.1
      port: 3306
      username: root
      password: 
      dbname: mini_project
      adapter: mysql
  redis:
    db:
      host: 127.0.0.1
      port: 6379
      password: